services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  flaskapp:
    image: flaskapp
    restart: always
    depends_on:
      - postgres
    ports:
      - 80:80
